name: Deploy Theme to WP Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Deploy theme
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.WPE_SFTP_HOST }}
          username: ${{ secrets.WPE_SFTP_USERNAME }}
          password: ${{ secrets.WPE_SFTP_PASSWORD }}
          port: 2222
          local_path: ./
          remote_path: /wp-content/themes/heru/